name       : sbcl
version    : 1.4.10
release    : 4
source     :
    - https://sourceforge.net/projects/sbcl/files/sbcl/1.4.10/sbcl-1.4.10-source.tar.bz2/download : 904ee7e90fd6d66dfb4da578ec9e3dab1a2a49b61b13fa1fbf30ce8b80593cc9
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
