name       : sbcl
version    : 2.1.2
release    : 9
source     :
    - http://prdownloads.sourceforge.net/sbcl/sbcl-2.1.2-source.tar.bz2 : b7710550939855ed49598c4a014483ed120b6991658a2a3b6afa47713dce4c0b
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr --with-sb-thread --with-sb-core-compression
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
