name       : sbcl
version    : 1.4.9
release    : 3
source     :
    - https://sourceforge.net/projects/sbcl/files/sbcl/1.4.9/sbcl-1.4.9-source.tar.bz2/download : 8f679eba0a5a8d86feced6776e389cc791a26998e4b43185a5e02bebb76620c5
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
