name       : sbcl
version    : 2.1.10
release    : 10
source     :
    - http://prdownloads.sourceforge.net/sbcl/sbcl-2.1.10-source.tar.bz2 : eb183f0f59a5cb2cbed762ec062bc34b9b6214b65402660784ef54838884b138
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr --with-sb-thread --with-sb-core-compression
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
