name       : sbcl
version    : 1.3.19
release    : 2
source     :
    - https://sourceforge.net/projects/sbcl/files/sbcl/1.3.19/sbcl-1.3.19-source.tar.bz2/download : b5eb98537aaa7afe24851a6da2f65798c6607e975062618dba33fa3a087fc018
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
