name       : sbcl
version    : 2.0.5
release    : 7
source     :
    - http://prdownloads.sourceforge.net/sbcl/sbcl-2.0.5-source.tar.bz2 : 0050f88dd12893c90f03e7b6c3b998929dcd08e7bb0ca5c4003be6110337e2cb
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - sbcl
build      : |
    ./make.sh --prefix=/usr --with-sb-thread --with-sb-core-compression
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
