name       : sbcl
version    : 2.3.5
release    : 13
source     :
    - http://prdownloads.sourceforge.net/sbcl/sbcl-2.3.5-source.tar.bz2 : 89c90720cf9d05dbcd90d690e381a2514c0f1807159e0d7222220c5a8c2d5186
license    :
    - BSD-3-Clause
    - MIT
component  : programming
summary    : Steel Bank Common LISP
description: |
    A high performance Common Lisp compiler. In addition to standard ANSI Common Lisp, it provides an interactive environment including an a debugger, a statistical profiler, a code coverage tool, and many other extensions.
builddeps  :
    - pkgconfig(libzstd)
    - sbcl
build      : |
    ./make.sh --prefix=/usr --with-sb-thread --with-sb-core-compression
install    : |
    INSTALL_ROOT=$installdir/usr ./install.sh
    rmdir $installdir/usr/share/doc/sbcl/html
    rmdir $installdir/usr/share/info
